name: mixpanel_flutter
description: Official Flutter Tracking SDK for Mixpanel Analytics developed and maintained by Mixpanel, Inc.
version: 1.0.1
homepage: https://mixpanel.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mixpanel.mixpanel_flutter
        pluginClass: MixpanelFlutterPlugin
      ios:
        pluginClass: MixpanelFlutterPlugin
